services:
  server:
    build: ./server
    container_name: my_server
    ports:
      - "9100:9100"

  client:
    build: ./client
    container_name: my_client
    environment:
      - SERVER_HOST=server # Questo deve corrispondere al nome del servizio sopra
    depends_on:
      - server